<a href="https://colab.research.google.com/github/Fredf23/TatChim/blob/main/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22TatHim_AutoML_18_23_05%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install autokeras

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 122.7/122.7 kB 2.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.1/129.1 kB 15.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 570.5/570.5 kB 21.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 34.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 311.2/311.2 kB 16.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 950.8/950.8 kB 32.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 49.7 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 589.8/589.8 MB 815.4 kB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 96.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 88.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.5/5.5 MB 87.6 MB/s eta 0:00:00
  Attempting uninstall: ml-dtypes
    Found existing installation: ml-dtypes 0.2.0
    Uninstalling ml-dtyp

In [ ]:
!pip freeze > requirements.txt

In [ ]:
import gdown
gdown.download('https://drive.google.com/uc?id=1evvQz66W5wPFpgdY_cGHEbC445YZfOGh', None, quiet=True)

'tathim_dataset.csv'

In [ ]:
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np


data = pd.read_csv("tathim_dataset.csv", decimal=',')
data=data.dropna()
print(data.shape)
print(data.info())

max_column=[]
for i in range(data.shape[1]):
  max_column.append(data.iloc[:,i].max())
  data.iloc[:,i]/=max_column[i]

print(max_column)

x_data = data.iloc[:,7:17]
y_data = data.iloc[:,0:7]

x_data=np.array(x_data)
y_data=np.array(y_data)

print(x_data.shape, y_data.shape)
data.isnull().any()

(8499, 16)
<class 'pandas.core.frame.DataFrame'>
Index: 8499 entries, 0 to 8499
Data columns (total 16 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   k_1     8499 non-null   float64
 1   k_2     8499 non-null   float64
 2   k_3     8499 non-null   float64
 3   k_4     8499 non-null   float64
 4   k_5     8499 non-null   int64  
 5   k_6     8499 non-null   int64  
 6   k_7     8499 non-null   float64
 7   h_1     8499 non-null   float64
 8   h_2     8499 non-null   float64
 9   h_3     8499 non-null   float64
 10  h_4     8499 non-null   float64
 11  h_5     8499 non-null   int64  
 12  h_6     8499 non-null   float64
 13  h_7     8499 non-null   float64
 14  h_8     8499 non-null   float64
 15  h_9     8499 non-null   float64
dtypes: float64(13), int64(3)
memory usage: 1.1 MB
None
[97.94, 0.11, 0.11, 2.3, 20, 20, 16.0, 11.6, 19.6, 1.03, 26.1, 2512, 39.6, 4.2, 1.14, 1.17]
(8499, 9) (8499, 7)


k_1    False
k_2    False
k_3    False
k_4    False
k_5    False
k_6    False
k_7    False
h_1    False
h_2    False
h_3    False
h_4    False
h_5    False
h_6    False
h_7    False
h_8    False
h_9    False
dtype: bool

In [ ]:
x_train, x_test, y_train, y_test = train_test_split(x_data, y_data, test_size=0.10, shuffle=True)
print('train - ',x_train.shape, y_train.shape)
print('test - ',x_test.shape, y_test.shape)

train -  (7649, 9) (7649, 7)
test -  (850, 9) (850, 7)


In [ ]:
print('X =', end=' ')
for p in x_train[0]:
  print(round(p,2), end='  ')

print()
print('Y =', end=' ')
for p in y_train[0]:
  print(round(p,2), end='  ')

X = 0.93  0.23  0.92  0.89  0.87  0.66  0.9  0.69  0.81  
Y = 0.79  1.0  1.0  0.93  0.8  0.0  0.25  

In [ ]:
import autokeras as ak

In [ ]:
tuner='greedy' #best loss=0.05
#tuner='bayesian' #best loss=0.05
#tuner='hyperband' #best loss=0.05
#tuner='random' #best loss=0.05

# Определение структуры входных данных
inputs = ak.Input()
outputs = ak.RegressionHead()

# Создание экземпляра AutoModel
model = ak.AutoModel(
    inputs=inputs,
    outputs=outputs,
    project_name="tathim",
    overwrite=True,
    max_trials=15,
    objective="val_loss",
    tuner=tuner
    )

In [ ]:
#batch_size=16 #Loss=0.05
batch_size=64 #Loss=0.05
#batch_size=128 #Loss=0.05
#batch_size=512 #Loss=0.05

# Компиляция и обучение модели
model.fit(x_train, y_train, epochs=100, validation_split=0.2, batch_size=batch_size)

Trial 15 Complete [00h 00m 12s]
val_loss: 0.04946647956967354

Best val_loss So Far: 0.04942214488983154
Total elapsed time: 00h 03m 13s
Epoch 1/100
120/120 ━━━━━━━━━━━━━━━━━━━━ 7s 28ms/step - loss: 0.2189 - mean_squared_error: 0.2189
Epoch 2/100
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0854 - mean_squared_error: 0.0854
Epoch 3/100
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0741 - mean_squared_error: 0.0741
Epoch 4/100
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0687 - mean_squared_error: 0.0687
Epoch 5/100
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0655 - mean_squared_error: 0.0655
Epoch 6/100
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0627 - mean_squared_error: 0.0627
Epoch 7/100
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0621 - mean_squared_error: 0.0621
Epoch 8/100
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0605 - mean_squared_error: 0.0605
Epoch 9/100
120/120 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0591 - mean_squared_err

In [ ]:
model.evaluate(x_test, y_test)

/usr/local/lib/python3.10/dist-packages/keras/src/saving/saving_lib.py:415: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 14 variables. 
  saveable.load_own_variables(weights_store.get(inner_path))


27/27 ━━━━━━━━━━━━━━━━━━━━ 1s 12ms/step - loss: 0.0535 - mean_squared_error: 0.0535


[0.05249105393886566, 0.05249105393886566]

In [ ]:
# First we export the model to a keras model
keras_model = model.export_model()

# Now, we ask for the model Sumary:
keras_model.summary()

keras_model.save(f"model_tun_{tuner}___bs_{batch_size}.keras")

Model: "functional_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ input_layer (InputLayer)             │ (None, 9)                   │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ cast_to_float32 (CastToFloat32)      │ (None, 9)                   │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense (Dense)                        │ (None, 256)                 │           2,560 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ re_lu (ReLU)                         │ (None, 256)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout (Dropout)                    │ (None, 256)                 │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 32)                  │           8,224 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ re_lu_1 (ReLU)                       │ (None, 32)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dropout_1 (Dropout)                  │ (None, 32)                  │               0 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ regression_head_1 (Dense)            │ (None, 7)                   │             231 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 11,015 (43.03 KB)

 Trainable params: 11,015 (43.03 KB)

 Non-trainable params: 0 (0.00 B)

Saved artifact at 'model_tun_greedy___bs_64.keras'. The following endpoints are available:

* Endpoint 'serve'
  args_0 (POSITIONAL_ONLY): TensorSpec(shape=(None, 9), dtype=tf.float32, name='keras_tensor')
Output Type:
  TensorSpec(shape=(None, 7), dtype=tf.float32, name=None)
Captures:
  132515327743904: TensorSpec(shape=(), dtype=tf.resource, name=None)
  132517529237488: TensorSpec(shape=(), dtype=tf.resource, name=None)
  132517529467392: TensorSpec(shape=(), dtype=tf.resource, name=None)
  132517529464928: TensorSpec(shape=(), dtype=tf.resource, name=None)
  132515326184432: TensorSpec(shape=(), dtype=tf.resource, name=None)
  132515326184256: TensorSpec(shape=(), dtype=tf.resource, name=None)


In [ ]:
predicted_y = model.predict(x_test)
print(predicted_y)

test_scores = model.evaluate(x_test, y_test, verbose=2)
print('Test loss:', test_scores[0])
print('Test accuracy:', test_scores[1])

 1/27 ━━━━━━━━━━━━━━━━━━━━ 3s 128ms/step

/usr/local/lib/python3.10/dist-packages/keras/src/saving/saving_lib.py:415: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 14 variables. 
  saveable.load_own_variables(weights_store.get(inner_path))


27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step
27/27 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step
[[0.83571273 0.9047813  0.89824075 ... 0.23182292 0.26574615 0.3312804 ]
 [0.8397914  0.9091435  0.9024695  ... 0.23581487 0.26469326 0.34371364]
 [0.8404282  0.91080374 0.90136796 ... 0.23696361 0.26444253 0.34322843]
 ...
 [0.8392856  0.90815616 0.9022604  ... 0.23466927 0.2649136  0.33675188]
 [0.8403592  0.90350664 0.90161276 ... 0.22965387 0.2706148  0.3219838 ]
 [0.83256066 0.9071999  0.8954029  ... 0.24278243 0.2585619  0.34415668]]
27/27 - 0s - 14ms/step - loss: 0.0525 - mean_squared_error: 0.0525
Test loss: 0.05249105393886566
Test accuracy: 0.05249105393886566


In [ ]:
query=x_test[50]
check=y_test[50]
query=np.array(query).reshape(-1,9)
pred = model.predict(query)[0]
query=query[0]
print('X       =', end=' ')
for i in range(len(query)):
  print(round(query[i]*max_column[i+7],2), end='  ')

print()
print('Predict =', end=' ')
for i in range(len(pred)):
  print(round(pred[i]*max_column[i],2), end='  ')

print()
print('Y       =', end=' ')
for i in range(len(check)):
  print(round(check[i]*max_column[i],2), end='  ')

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 144ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step
X       = 9.7  7.5  0.9  23.6  1366.0  24.4  4.1  1.11  0.81  
Predict = 82.18  0.1  0.1  1.99  4.67  5.32  5.49  
Y       = 75.04  0.11  0.1  1.75  16.0  0.0  7.0  